### PR TITLE
add GetAccountBrowserTrackerIDs

### PR DESCRIPTION
**Pull request by ProGenshinImpactPlayer**
useful if you want to check which account is for which process

### CODE REVIEW

**Comment by ic3w0lf22** [comment]
I'll be removing the `AllowGetAccountBrowserTrackerIDs` setting as the browser tracker ID assigned to an account is a completely random number. I'll also be changing the return type to a JSON object

**Comment by SushiLeader** [comment]
It will allow people to get accounts without using GetAccounts

**Comment by ic3w0lf22** [comment]
Good point, how about asking for a specific user instead of getting all tracker IDs and only allow getting all the information if AllowGetAccounts is enabled?

**Comment by SushiLeader** [comment]
Yea I think that would be fine.

**Comment by SushiLeader** [comment]
the new commit is for fixing the issue that Roblox launcher doesn't exit even after the game launched

**Pull request closed without merging**
