### PR TITLE
Nexus Changes

### PR DESCRIPTION
**Pull request by bloxain**
list of changes 
1.you can now use commands in lower and upercase
2.Preformace no longer runs right away if the window is not in use(helps me but you can remove this)
3. fixed issue i was haveing where Preformace keeps running even when the window is open for the first time

### CODE REVIEW

**Comment by bloxain** [comment]
i mostly made this for one of my scripts and the fact i have Preformace in autoexec so some changes may not make sense

**Review by ic3w0lf22 — CHANGES_REQUESTED** [review]
fix spacing

**Comment by bloxain** [comment]
What? Where

**Comment by bloxain** [comment]
You can edit and add yourself if you want to

**Comment by bloxain** [comment]
new changes(becuse i don't want to create another pull)
1.kills the extra roblox processes thats currently just takeing up ram and cpu

**Comment by ic3w0lf22** [comment]
Freezes the main thread, bad implementation.

**Pull request closed without merging**
